% This script experiments with sensitivity to spike jitter AND NOISE SPIKES
% with varying ISI COVs

useBandLimitedJitter = 0;

mix = [0 1 0; 1 8 0; 1 1 0; 1 0 0; 3 0 1; 1 0 1; 1 0 5]; %weights for combining Poisson, regular, and burst firing 

% jitter (s), noise spikes (proportion of base pattern)
noise = [0 .25; ... 
        0 .5; ...
        0 1; ...
        .004 .25; ...
        .004 .5; ...
        .004 1; ...
        ] 

doCOV(mix, noise, 'data_COVNS', useBandLimitedJitter)

